services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx-test5
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - 80:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask:0.0.1
    container_name: flask-test5
    volumes:
      - ./code/:/code/
      - ./uploads/:/uploads/ # Volumen para almacenamiento de archivos
    environment:
      - FLASK_APP=/code/main.py
      - SECRET_KEY=mensaje_encriptado_mortadela_jaja
      # Variables para Flask-Limiter
      - RATELIMIT_HEADERS_ENABLED=true # Agrega headers para indicar estado de límite
      # Variables de conexión a la base de datos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=docker_postgres_db5
    command: flask run --host=0.0.0.0
    networks:
      my-network:
        aliases:
          - flask-app
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: docker-postgres5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker_postgres_db5
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports: #pasar del puerto interno 5432 al 5432 de mi PC
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
